### ISSUE TITLE
NIP1 Need a better DApp website with full set of Oracle status data display and analysis

### ISSUE THREAD

**Issue by zhangzhongnan928** [NEST-Protocol/nips#1]
- Combine the NEST website and the NEST DApp website
- update key "selling point" of NEST Oracle
- update Key "selling point" of NEST token
- Better DApp UX for the non-professional miners
- Better DApp UX for NEST holders
- Oracle status data display
- Oracle data analysis display

**Comment by AndyChenW** [comment]
Thanks for first NIP, but AFAIK, this PR is more likely to specific to different level things:

- Combine the NEST website and the NEST DApp website
This should be a PR for nestprotocol.org for discussion, I am pushing the Nest Team to new a project for opensourcing the website.
- update key "selling point" of NEST Oracle
- update Key "selling point" of NEST token
- Better DApp UX for the non-professional miners
- Better DApp UX for NEST holders
- Oracle status data display
- Oracle data analysis display
All the above proposal IMO should be PRs for website/iOS/Android App projects.

I think the nips should more focus on the protocol level and protocol implementation layer improvement. This is a NIP project but it's more likely the Nest Protocol Improvement Proposal, any website and App layer improvement layer not related to the protocol should not be here.

See what bip as example, https://github.com/bitcoin/bips.

And the number of NIP like (1) would be confirmed after discussion and get confirmed by the community.

So thanks, if you agree with those above, I am going to close this issue, and refer this issue after the opensourcing of nestprotocol website/iOS/Android project.

**Comment by AndyChenW** [comment]
@NestProtocol would you please opensource and new three projects? nestprotocol.org website, iOS and Android. Then we can make improvement there.

**Comment by AndyChenW** [comment]
@zhangzhongnan928

the web project is opensourced, you can add a issue of web there.
https://github.com/NEST-Protocol/NEST-oracle-V3-web
